### ISSUE TITLE
first hoverfly-java should check the status of application/service, if application is up request always goes to application and also capture the response but if application/service is down then hoverfly-java should simulate the recorded response.

### ISSUE THREAD

**Issue by antika08** [SpectoLabs/hoverfly-java#208]
Please use: https://gitter.im/SpectoLabs/hoverfly for questions about `Hoverfly`.

Only posts that are bug reports or feature/enhancement requests will be addressed here.

first hoverfly-java should check the status of application/service, if application is up request always goes to application and also capture the response but if application/service is down then hoverfly-java should simulate the recorded response.

**Comment by antika08** [comment]
Please help me for this.

**Comment by tommysitu** [comment]
Ok, something like this: 
```
 private RestTemplate restTemplate = new RestTemplate();

    private Hoverfly hoverfly;
    @Before
    public void setUp() {


        try {
            restTemplate.getForEntity("https://your-endpoint", Void.class);
            hoverfly = new Hoverfly(HoverflyMode.CAPTURE);
        } catch (RestClientException e) {
            hoverfly.setMode(HoverflyMode.SIMULATE);
            hoverfly.simulate(SimulationSource.file(Paths.get("output/simulation.json")));
        }

    }

    @After
    public void tearDown() {
        if (hoverfly != null && hoverfly.getMode() == HoverflyMode.CAPTURE) {
            hoverfly.exportSimulation(Paths.get("output/simulation.json"));
        }
    }

```

Replace `RestTemplate` with the HTTP Client you are using.

**Comment by antika08** [comment]
Hi,

I tried to execute below code:

 private RestTemplate restTemplate = new RestTemplate();
	    private Hoverfly hoverfly;

	    @Before
	    public void setUp() {
	        try {
	            restTemplate.getForEntity("https://jsonplaceholder.typicode.com/todos/1", Void.class);
	            hoverfly = new Hoverfly(HoverflyMode.CAPTURE);
	        } catch (RestClientException e) {
	            hoverfly.setMode(HoverflyMode.SIMULATE);
	            hoverfly.simulate(SimulationSource.file(Paths.get("output/simulation.json")));
	        }

	    }

	    @After
	    public void tearDown() {
	        if (hoverfly != null && hoverfly.getMode() == HoverflyMode.CAPTURE) {
	            hoverfly.exportSimulation(Paths.get("output/simulation.json"));
	        }
	    }
	    
		 @Test
		 public void test2() {
			 
			//RestTemplate restTemplate = new RestTemplate();
			 String fooResourceUrl
			   = "https://jsonplaceholder.typicode.com/todos/";
			 ResponseEntity<String> response
			   = restTemplate.getForEntity(fooResourceUrl + "/1", String.class);
			String body = response.getBody(); 
			System.out.println("Body: "+body);
			 
		 }
		 
				 
	 }

But still getting below error:
io.specto.hoverfly.junit.api.HoverflyClientException: Failed to get config information: Failed to connect to localhost/0:0:0:0:0:0:0:1:60565
	at io.specto.hoverfly.junit.api.OkHttpHoverflyClient.getConfigInfo(OkHttpHoverflyClient.java:246)
	at io.specto.hoverfly.junit.core.Hoverfly.getMode(Hoverfly.java:442)
	at com.in28minutes.springboot.controller.StudentControllerTest.tearDown(StudentControllerTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by tommysitu** [comment]
After you initialize a new Hoverfly, you need to call `hoverfly.start()` as well.

**Comment by antika08** [comment]
We have tried below code:

@Before
	    public void setUp() {
	    //	HoverflyConfig.localConfigs().proxyPort(8080);
	        try {
	            restTemplate.getForEntity("https://jsonplaceholder.typicode.com/todos/2", Void.class);
	            System.out.println("inside try");
	            hoverfly = new Hoverfly(HoverflyMode.CAPTURE);
	            hoverfly.start();
	        } catch (RestClientException e) {
	        	System.out.println("inside catch");
	        	hoverfly = new Hoverfly(HoverflyMode.SIMULATE);
	          //  hoverfly.setMode(HoverflyMode.SIMULATE);
	            hoverfly.start();
	            hoverfly.simulate(SimulationSource.file(Paths.get("C:\\Users\\ac00497927\\workspace-spring-tool-suite-4-4.1.0.RELEASE\\com.in28minutes.springboot-2\\src\\test\\resources\\hoverfly\\simulation.json")));
	        }

	    }
	    
	   
	    @After
	    public void tearDown() {
	        if (hoverfly != null && hoverfly.getMode() == HoverflyMode.CAPTURE) {
	            hoverfly.exportSimulation(Paths.get("C:\\Users\\ac00497927\\workspace-spring-tool-suite-4-4.1.0.RELEASE\\com.in28minutes.springboot-2\\src\\test\\resources\\hoverfly\\simulation.json"));
	        }
	    }
	    
		 @Test
		 public void test2() {
			 
			//RestTemplate restTemplate = new RestTemplate();
			 String fooResourceUrl
			   = "https://jsonplaceholder.typicode.com/todos/";
			 ResponseEntity<String> response
			   = restTemplate.getForEntity(fooResourceUrl + "/2", String.class);
			String body = response.getBody(); 
			System.out.println("Body: "+body);
			 
		 }
		 
		 
		 
				 
	 }

its working for single API service but if we want to check the status of multiple services, how can we proceed with above code.
 Please guide me.

**Comment by antika08** [comment]
please help us to check the status for multiple services.

**Comment by antika08** [comment]
Hi tommysitu,

Please help us to check the status for post & get method of multiple services.

Thanks & Regards,
Antika Chauhan

**Comment by JohnFDavenport** [comment]
@antika08 @tommysitu does not work for you. What you are asking for support that is in excess of what anyone can reasonably expect from an open source project. Whilst we have been helpful to continue to do so free of charge would mean diverting limited resources away from the wider community SpectoLabs seeks to serve. If your company would like to enter into a commercial support arrangement with SpectoLabs please get in contact with myself. My email is on my profile page. Alternatively use the [SpectoLabs contact form](https://specto.io/support/).
