### ISSUE TITLE
Allow specifying a working directory for HoverflyExtension

### ISSUE THREAD

**Issue by ciscoo** [SpectoLabs/hoverfly-java#236]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/SpectoLabs/hoverfly-java/issues/232

I have written a smoke test for an internal library I am working on at my company.
The test utilizes the `HoverflyExtension` for JUnit 5 tests as shown below:

```java
@HoverflySimulate(source = @Source(value = "simulation.json", type = SourceType.CLASSPATH))
@ExtendWith(HoverflyExtension.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class ApplicationSmokeTests {

	@Test
	void smokeTest() {
		// test logic
	}

}
```

The tests works perfectly locally, but fails when running in Jenkins:

```stacktrace
java.lang.IllegalStateException: Could not start Hoverfly process
	at io.specto.hoverfly.junit.core.Hoverfly.startHoverflyProcess(Hoverfly.java:259)
	at io.specto.hoverfly.junit.core.Hoverfly.start(Hoverfly.java:140)
	at io.specto.hoverfly.junit5.HoverflyExtension.beforeAll(HoverflyExtension.java:114)
	... snip
Caused by: org.zeroturnaround.exec.ProcessInitException: Could not execute [/tmp/hoverfly.8333148746451382693/hoverfly_linux_amd64, -pp, 36316, -ap, 46318, -logs, json, -log-level, info] in /tmp/hoverfly.8333148746451382693. Error=13, Permission denied
	at org.zeroturnaround.exec.ProcessInitException.newInstance(ProcessInitException.java:80)
	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:1022)
	at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:989)
	at org.zeroturnaround.exec.ProcessExecutor.start(ProcessExecutor.java:961)
	at io.specto.hoverfly.junit.core.Hoverfly.startHoverflyProcess(Hoverfly.java:257)
	... 62 more
Caused by: java.io.IOException: Cannot run program "/tmp/hoverfly.8333148746451382693/hoverfly_linux_amd64" (in directory "/tmp/hoverfly.8333148746451382693"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:1016)
	... 65 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 66 more
```

Like the issue linked above, `/tmp` is a system folder and my company does not allow Jenkins to have relevant permissions to `/tmp`.

**Describe the solution you'd like**

From looking into the code, it appears that it may be possible to specify a _working directory_. Specifically the `binaryLocation` field: https://github.com/SpectoLabs/hoverfly-java/blob/0.13.0/src/main/java/io/specto/hoverfly/junit/core/config/HoverflyConfiguration.java#L43

Looks like that field gets configured here:

https://github.com/SpectoLabs/hoverfly-java/blob/0.13.0/src/main/java/io/specto/hoverfly/junit/core/Hoverfly.java#L170..L173

with the help of https://github.com/SpectoLabs/hoverfly-java/blob/0.13.0/src/main/java/io/specto/hoverfly/junit/core/TempFileManager.java

So if we were able to configure this value declaratively with annotations (`@HoverflyConfig`?) or some environment variable, then that should solve the permission issue with `/tmp`.

**Describe alternatives you've considered**

* Disable the test entirely when running on Jenkins
* Avoid using `HoverflyExtension` and manually configure Hoverfly for test

**Additional context**

N/A

**Comment by ciscoo** [comment]
For point 2, I've managed to bypass `/tmp` restrictions folder entirely with the following:

```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class ApplicationSmokeTests {

	@BeforeAll
	static void beforeAll() {
		Path workingDir;
		if (System.getenv().containsKey("HOVERFLY_WORK_DIR")) {
			workingDir = Paths.get(System.getenv("HOVERFLY_WORK_DIR"));
		}
		else {
			workingDir = Paths.get(System.getProperty("user.dir"));
		}
		hoverfly = new Hoverfly(localConfigs().binaryLocation(workingDir.toString()), HoverflyMode.SIMULATE);
		hoverfly.start();
		hoverfly.simulate(SimulationSource.classpath("simulation.json"));
	}

	@AfterAll
	static void afterAll() {
		hoverfly.close();
	}

	@Test
	void smokeTest() {
		// test logic
	}

}
```

**Comment by tommysitu** [comment]
Hi @ciscoo, you are on the right track that `binaryLocation` lets you specify the location of hoverfly, I will add it to the junit5 config this week.

**Comment by tommysitu** [comment]
The binaryLocation config option is available in master
