### ISSUE TITLE
Failed to delete Hoverfly binaries on Windows machine

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly-java#50]
An issue reported by Bas Dijkstra: 

I keep getting an error message when hoverfly tries to delete the
temporary binary. It has created the stub successfully though (tested that
with a REST Assured test).

Any thoughts? Here's the error stack trace.
```
java.lang.IllegalStateException: Failed to delete hoverfly binary
	at io.specto.hoverfly.junit.core.Hoverfly.stop(Hoverfly.java:163)
	at io.specto.hoverfly.junit.rule.HoverflyRule.after(HoverflyRule.java:183)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.nio.file.AccessDeniedException:
C:\Users\Bas\AppData\Local\Temp\hoverfly_windows_amd64.exe132150163173896543
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at io.specto.hoverfly.junit.core.Hoverfly.stop(Hoverfly.java:161)
	... 10 more
```

**Comment by tommysitu** [comment]
The running environment is Win8.1, 64bit
